// GENERATED by scripts/import-videos.mjs — do not edit by hand.
// Regenerate with: npm run import:videos
//
// HELD BACK: 28 videos.
//   Travel: youtube watermark burned into the picture
//   Meditation: files are ~265 MB each and stream with the moov atom at the end, so they cannot be verified or played progressively — needs re-encoding before it ships

export type Video = {
  slug: string;
  title: string;
  category: string;
  descEn: string;
  videoUrl: string;
  duration: number;
  poster: string | null;
  posterLg: string | null;
};

export type VideoCategory = {
  slug: string;
  label: { es: string; en: string };
  count: number;
};

export const videoCategories: VideoCategory[] = [
  {
    "slug": "documentales",
    "label": {
      "es": "Documentales",
      "en": "Documentaries"
    },
    "count": 10
  },
  {
    "slug": "musica",
    "label": {
      "es": "Música",
      "en": "Music"
    },
    "count": 4
  }
];

export const videos: Video[] = [
  {
    "slug": "prelude-in-c-major-by-johann-sebastian-bach-at-the-beach",
    "title": "Prelude in C Major by Johann Sebastian Bach at the Beach",
    "category": "musica",
    "descEn": "Enjoy Bach’s timeless Prelude in C Major accompanied by peaceful seaside scenery.",
    "videoUrl": "https://video.mobiogames.com/new+videos/Music/BeachSide-JohannSebastianBach-PreludeinCMajor.mp4",
    "duration": 132,
    "poster": "/videos/prelude-in-c-major-by-johann-sebastian-bach-at-the-beach.webp",
    "posterLg": "/videos/prelude-in-c-major-by-johann-sebastian-bach-at-the-beach@lg.webp"
  },
  {
    "slug": "bugatti-step-by-jaroslav-jezek-in-the-rainforest",
    "title": "Bugatti Step by Jaroslav Ježek in the Rainforest",
    "category": "musica",
    "descEn": "Experience Jaroslav Ježek’s lively Bugatti Step set against the lush sounds and scenery of a rainforest.",
    "videoUrl": "https://video.mobiogames.com/new+videos/Music/Rainforest-JaroslavJez%CC%8Cek-Bugattistep.mp4",
    "duration": 161,
    "poster": "/videos/bugatti-step-by-jaroslav-jezek-in-the-rainforest.webp",
    "posterLg": "/videos/bugatti-step-by-jaroslav-jezek-in-the-rainforest@lg.webp"
  },
  {
    "slug": "rondo-alla-turca-by-wolfgang-amadeus-mozart-on-a-rainy-day",
    "title": "Rondo Alla Turca by Wolfgang Amadeus Mozart on a Rainy Day",
    "category": "musica",
    "descEn": "Listen to Mozart’s energetic Rondo Alla Turca while relaxing in the atmosphere of a rainy day.",
    "videoUrl": "https://video.mobiogames.com/new+videos/Music/Rainy-RondoAllaTurca-Mozart.mp4",
    "duration": 209,
    "poster": "/videos/rondo-alla-turca-by-wolfgang-amadeus-mozart-on-a-rainy-day.webp",
    "posterLg": "/videos/rondo-alla-turca-by-wolfgang-amadeus-mozart-on-a-rainy-day@lg.webp"
  },
  {
    "slug": "storm-by-antonio-vivaldi-on-a-windy-day",
    "title": "Storm by Antonio Vivaldi on a Windy Day",
    "category": "musica",
    "descEn": "Feel the intensity of Vivaldi’s Storm paired with dramatic windswept scenery.",
    "videoUrl": "https://video.mobiogames.com/new+videos/Music/Windy-AntonioVivaldi-Storm.mp4",
    "duration": 177,
    "poster": "/videos/storm-by-antonio-vivaldi-on-a-windy-day.webp",
    "posterLg": "/videos/storm-by-antonio-vivaldi-on-a-windy-day@lg.webp"
  },
  {
    "slug": "why-do-we-yawn",
    "title": "Why Do We Yawn?",
    "category": "documentales",
    "descEn": "Discover why we yawn and what this familiar reflex reveals about the human body.",
    "videoUrl": "https://video.mobiogames.com/new+videos/Documentary/WhyDoWeYawn.mp4",
    "duration": 72,
    "poster": "/videos/why-do-we-yawn.webp",
    "posterLg": "/videos/why-do-we-yawn@lg.webp"
  },
  {
    "slug": "the-secret-life-of-bananas",
    "title": "The Secret Life of Bananas",
    "category": "documentales",
    "descEn": "Explore the surprising journey of bananas, from tropical plants to one of the world’s favourite fruits.",
    "videoUrl": "https://video.mobiogames.com/new+videos/Documentary/TheSecretLifeofBananas.mp4",
    "duration": 72,
    "poster": "/videos/the-secret-life-of-bananas.webp",
    "posterLg": "/videos/the-secret-life-of-bananas@lg.webp"
  },
  {
    "slug": "why-cats-knock-things-over",
    "title": "Why Cats Knock Things Over",
    "category": "documentales",
    "descEn": "Find out why cats push objects from surfaces and what this curious behaviour may reveal.",
    "videoUrl": "https://video.mobiogames.com/new+videos/Documentary/WhyCatsKnockThingsOver.mp4",
    "duration": 72,
    "poster": "/videos/why-cats-knock-things-over.webp",
    "posterLg": "/videos/why-cats-knock-things-over@lg.webp"
  },
  {
    "slug": "how-wi-fi-travels-through-walls",
    "title": "How Wi-Fi Travels Through Walls",
    "category": "documentales",
    "descEn": "See how Wi-Fi signals move through walls to keep our devices connected.",
    "videoUrl": "https://video.mobiogames.com/new+videos/Documentary/HowWi-FiTravelsThroughWalls.mp4",
    "duration": 72,
    "poster": "/videos/how-wi-fi-travels-through-walls.webp",
    "posterLg": "/videos/how-wi-fi-travels-through-walls@lg.webp"
  },
  {
    "slug": "the-day-plastic-took-over-the-world",
    "title": "The Day Plastic Took Over the World",
    "category": "documentales",
    "descEn": "Explore how plastic transformed everyday life and created one of the world’s biggest environmental challenges.",
    "videoUrl": "https://video.mobiogames.com/new+videos/Documentary/TheDayPlasticTookOverTheWorld.mp4",
    "duration": 72,
    "poster": "/videos/the-day-plastic-took-over-the-world.webp",
    "posterLg": "/videos/the-day-plastic-took-over-the-world@lg.webp"
  },
  {
    "slug": "why-do-we-dream",
    "title": "Why Do We Dream?",
    "category": "documentales",
    "descEn": "Discover what happens while we dream and why the sleeping mind creates such vivid experiences.",
    "videoUrl": "https://video.mobiogames.com/new+videos/Documentary/WhyDoWeDream.mp4",
    "duration": 72,
    "poster": "/videos/why-do-we-dream.webp",
    "posterLg": "/videos/why-do-we-dream@lg.webp"
  },
  {
    "slug": "the-weird-history-of-toothpaste",
    "title": "The Weird History of Toothpaste",
    "category": "documentales",
    "descEn": "Trace the strange and fascinating evolution of toothpaste through history.",
    "videoUrl": "https://video.mobiogames.com/new+videos/Documentary/TheWeirdHistoryofToothpaste.mp4",
    "duration": 72,
    "poster": "/videos/the-weird-history-of-toothpaste.webp",
    "posterLg": "/videos/the-weird-history-of-toothpaste@lg.webp"
  },
  {
    "slug": "how-ants-run-a-tiny-empire",
    "title": "How Ants Run a Tiny Empire",
    "category": "documentales",
    "descEn": "Step inside the organised world of ants and discover how their tiny colonies function.",
    "videoUrl": "https://video.mobiogames.com/new+videos/Documentary/HowAntsRunaTinyEmpire.mp4",
    "duration": 72,
    "poster": "/videos/how-ants-run-a-tiny-empire.webp",
    "posterLg": "/videos/how-ants-run-a-tiny-empire@lg.webp"
  },
  {
    "slug": "why-popcorn-pops",
    "title": "Why Popcorn Pops",
    "category": "documentales",
    "descEn": "Discover the simple science that turns a hard corn kernel into fluffy popcorn.",
    "videoUrl": "https://video.mobiogames.com/new+videos/Documentary/WhyPopcornPops.mp4",
    "duration": 72,
    "poster": "/videos/why-popcorn-pops.webp",
    "posterLg": "/videos/why-popcorn-pops@lg.webp"
  },
  {
    "slug": "the-mystery-of-the-bermuda-triangle",
    "title": "The Mystery of the Bermuda Triangle",
    "category": "documentales",
    "descEn": "Explore the stories, theories, and enduring mystery surrounding the Bermuda Triangle.",
    "videoUrl": "https://video.mobiogames.com/new+videos/Documentary/TheMysteryoftheBermudaTriangle.mp4",
    "duration": 72,
    "poster": "/videos/the-mystery-of-the-bermuda-triangle.webp",
    "posterLg": "/videos/the-mystery-of-the-bermuda-triangle@lg.webp"
  }
];

export const videoBySlug = (slug: string): Video | undefined =>
  videos.find((v) => v.slug === slug);
